raise Exception('b.py is aborted')
